/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Repartidor;

import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;

/**
 *
 * @author defer
 */
public class OrdenesR extends javax.swing.JPanel {

    String codigo;
    
    public OrdenesR() {
        initComponents();
        
        mostrarOrdenes();
    }
    
    public void mostrarOrdenes(){
        LogicaRepartidor logica = new LogicaRepartidor();
        
        DefaultTableModel modelo = logica.mostrarOrdenes();
        
        tblOrdenes.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        btnEntregada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo1 = new javax.swing.JTextField();
        btnEnruta = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(880, 560));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdenes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 760, 380));

        btnEntregada.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnEntregada.setText("Entregada");
        btnEntregada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregadaActionPerformed(evt);
            }
        });
        add(btnEntregada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 160, 70));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Órdenes Pendientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        jLabel2.setText("Código/ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 70, -1));

        jLabel3.setText("Código/ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));
        add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 70, -1));

        btnEnruta.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnEnruta.setText("En ruta");
        btnEnruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrutaActionPerformed(evt);
            }
        });
        add(btnEnruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 160, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try{
            Connection conexion=null;
            conexion=getConnection();
            
            int fila = tblOrdenes.getSelectedRow();
            String codigo = tblOrdenes.getValueAt(fila, 0).toString();
            
            ps = conexion.prepareStatement("SELECT idOrdenes FROM ordenes where idOrdenes=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();
            
            while(rs.next()){
                codigo= (rs.getString("idOrdenes"));
                txtCodigo.setText(codigo);
            }
            
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_tblOrdenesMouseClicked

    private void btnEntregadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregadaActionPerformed
        PreparedStatement ps = null;

        try{
            Connection conexion = getConnection();
            
            ps = conexion.prepareStatement("update ordenes set estado='Finalizada' where idOrdenes=?");
            ps.setString(1, txtCodigo.getText());
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Orden actualizada correctamente");
            mostrarOrdenes();
            

        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_btnEntregadaActionPerformed

    private void btnEnrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrutaActionPerformed
        PreparedStatement ps = null;

        try{
            Connection conexion = getConnection();
            
            ps = conexion.prepareStatement("update ordenes set estado='En ruta' where idOrdenes=?");
            ps.setString(1, txtCodigo.getText());
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Orden actualizada correctamente");
            mostrarOrdenes();
            

        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_btnEnrutaActionPerformed

    public static final String URL = "jdbc:mysql://localhost:3306/pizzeriapp?autoReconnet=true&useSSL=false";
    public static final String usuario = "root";
    public static final String contraseña = "12345";
    PreparedStatement ps;
    ResultSet rs; 
    
    public java.sql.Connection getConnection(){
        java.sql.Connection conexion=null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = (java.sql.Connection) DriverManager.getConnection(URL,usuario,contraseña);
            System.err.println("Conectado a la base de datos");
            
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
        
        return conexion;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnruta;
    private javax.swing.JButton btnEntregada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    // End of variables declaration//GEN-END:variables
}
