/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Cajero;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;


public class RealizarOrden extends javax.swing.JPanel {

    String orden = "";
    double total;
    
    public static final String URL = "jdbc:mysql://localhost:3306/pizzeriapp?autoReconnet=true&useSSL=false";
    public static final String usuario = "root";
    public static final String contraseña = "12345";
    PreparedStatement ps;
    ResultSet rs; 
    
    public RealizarOrden() {
        initComponents();
        
        rbtnSi.setSelected(true);
        
        cargar_ComboBox();
    }
    
    void cargar_ComboBox(){
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
             Connection conexion=null;
            conexion=getConnection();
            
           ps=conexion.prepareStatement("select NombreProducto from productos");
           rs=ps.executeQuery();
           
           while(rs.next()){
               cmbProd.addItem(rs.getString("NombreProducto"));
           }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }

    public Connection getConnection(){
        Connection conexion=null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion = (Connection) DriverManager.getConnection(URL,usuario,contraseña);
            JOptionPane.showMessageDialog(null, "Conexion exitosa");
            
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
        
        return conexion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpDomic = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnSi = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRealizar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        cmbProd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrden = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-nuevo-64.png"))); // NOI18N
        jLabel1.setText("REALIZAR ORDEN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 180, -1));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, -1));

        jLabel4.setText("¿Pedido a domicilio?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        rbtnSi.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDomic.add(rbtnSi);
        rbtnSi.setText("Sí");
        add(rbtnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        rbtnNo.setBackground(new java.awt.Color(255, 255, 255));
        btngrpDomic.add(rbtnNo);
        rbtnNo.setText("No");
        add(rbtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel5.setText("TOTAL:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setText("$00.00");
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        jLabel7.setText("Productos:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 180, -1));

        jLabel8.setText("Dirección:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setText("Teléfono:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        btnRealizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRealizar.setText("Realizar Orden");
        btnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarActionPerformed(evt);
            }
        });
        add(btnRealizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        btnReiniciar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        add(cmbProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, -1));

        txtOrden.setColumns(20);
        txtOrden.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtOrden.setRows(5);
        txtOrden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOrden.setEnabled(false);
        jScrollPane1.setViewportView(txtOrden);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 270, 220));

        jLabel10.setText("Orden:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        btnAdd.setText("Añadir a orden");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombre.setText("");
        cmbProd.setSelectedIndex(0);
        txtOrden.setText("");
        lblTotal.setText("$0.00");
        
        total = 0;
        orden = "";
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String prod = (String)cmbProd.getSelectedItem();
        orden+= prod+"\n";
        txtOrden.setText(orden);
        
         PreparedStatement ps = null;
        ResultSet rs = null;
        try{
             Connection conexion=null;
            conexion=getConnection();
            
           ps=conexion.prepareStatement("select precio from productos");
           rs=ps.executeQuery();
           
           while(rs.next()){
               lblTotal.setText(rs.getInt("precio"));
           }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public void limpiarCajas(){
        txtNombre.setText(null);
        txtDireccion.setText(null);
        txtOrden.setText(null);
        txtTelefono.setText(null);
        cmbProd.setSelectedIndex(0);
        lblTotal.setText("$0.00");
    }
    
    private void btnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarActionPerformed
        //String t = (String) total;
        
        Connection conexion = null;
        
        try{
            conexion = getConnection();
            ps = conexion.prepareStatement("insert into ordenes (NombreCliente,Orden,direccion,telefono,estado,Total) values(?,?,?,?,?,?)");
            ps.setString(1,txtNombre.getText());
            ps.setString(2,orden);
            ps.setString(3,txtDireccion.getText());
            ps.setString(4,txtTelefono.getText());
            ps.setString(5, "Activo");
            ps.setString(6, String.valueOf(total));
            int resultado = ps.executeUpdate(); //Ejecutamos la insercion
            
            if(resultado > 0){ //Se ejecuto correctamente la insercion
                JOptionPane.showMessageDialog(null, "Orden agregado correctamente");
                limpiarCajas();
                total = 0;
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al agregar el registro");
                limpiarCajas();
                total = 0;
            }
            
            conexion.close(); //Cerramos la conexion
            
        }catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_btnRealizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.ButtonGroup btngrpDomic;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSi;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtOrden;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
