package com.Admin;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class AdministradorMenu extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public AdministradorMenu() {
        initComponents();
        this.setSize(1100,700);
        this.PanelPrincipal.setSize(1100,750);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btnInvent = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnProv = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        barraPric = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        btnSalirtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        PanelPrincipal.setBackground(new java.awt.Color(255, 102, 102));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1060, 830));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-pizza-40.png"))); // NOI18N
        jButton4.setText("Productos");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, 160, 380));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gerente-40.png"))); // NOI18N
        jLabel1.setText("ADMINISTRADOR");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 369, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona la opcion a la que desea acceder");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 298, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-cerrar-ventana-30.png"))); // NOI18N
        jButton7.setText("Salir");
        PanelPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 804, 125, -1));

        btnInvent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-grocery-shelf-40.png"))); // NOI18N
        btnInvent.setText("Insumos");
        btnInvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnInvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 167, 380));

        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-personal-trainer-skin-type-2-40.png"))); // NOI18N
        btnEmpleados.setText("Usuarios");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 167, 167, 380));

        btnProv.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-proveedor-40.png"))); // NOI18N
        btnProv.setText("Proveedores");
        btnProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, 380));

        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-caja-registradora-40.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 167, 380));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion (1).png"))); // NOI18N
        btnLogout.setText("Cerrar Sesión");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 171, 49));

        btnCompras.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-producto-40.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCompras.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 167, 160, 380));

        barraPric.setBackground(new java.awt.Color(255, 255, 255));
        barraPric.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraPricMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                barraPricMouseMoved(evt);
            }
        });
        barraPric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraPricMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 153, 153));

        btnSalirtxt.setBackground(new java.awt.Color(255, 153, 153));
        btnSalirtxt.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        btnSalirtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalirtxt.setText("X");
        btnSalirtxt.setToolTipText("");
        btnSalirtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalirtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirtxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirtxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirtxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalirtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalirtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraPricLayout = new javax.swing.GroupLayout(barraPric);
        barraPric.setLayout(barraPricLayout);
        barraPricLayout.setHorizontalGroup(
            barraPricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPricLayout.createSequentialGroup()
                .addContainerGap(1065, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraPricLayout.setVerticalGroup(
            barraPricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelPrincipal.add(barraPric, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Productos prod = new Productos();
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnInventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventActionPerformed
        Insumos ins = new Insumos();
        ins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInventActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        Usuarios empl = new Usuarios();
        empl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvActionPerformed
        Int_Proveedores proveedores = new Int_Proveedores();
        proveedores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProvActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        Int_Ventas ventas = new Int_Ventas();
        ventas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        int_Compras compras = new int_Compras();
        compras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnSalirtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirtxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirtxtMouseClicked

    private void btnSalirtxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirtxtMouseEntered
        btnSalir.setBackground(Color.RED);
        btnSalirtxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalirtxtMouseEntered

    private void btnSalirtxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirtxtMouseExited
        btnSalir.setBackground(new Color(255,153,153));
        btnSalirtxt.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSalirtxtMouseExited

    private void barraPricMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPricMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraPricMouseDragged

    private void barraPricMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPricMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_barraPricMouseMoved

    private void barraPricMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraPricMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraPricMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel barraPric;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnInvent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProv;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel btnSalirtxt;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
